version: '3.7'
services:
  webapp:
    image: vanherpedries/webapp:latest
    #build: ./web
    command: uwsgi --ini app.ini
    expose:
      - 5000
  nginx:
    image: webapp-nginx
    build: ./nginx
    ports:
      - 8080:80
    depends_on:
      - webapp

