apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
    name: nginx
    namespace: webapp
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: nginx
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 75
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
    name: webapp
    namespace: webapp
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: webapp
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 75
