apiVersion: types.kubefed.io/v1beta1
kind: FederatedIngress
metadata:
  name: ingress
  namespace: webapp
spec:
  template:
    spec:
      rules:
      - host: 
        http:
          paths:
          - backend:
              serviceName: nginx
              servicePort: 80
  placement:
    clusters:
    - name: euw1
    - name: usc1
    - name: eks
