apiVersion: types.kubefed.io/v1beta1
kind: FederatedDeployment
metadata:
  name: nginx
  namespace: webapp
spec:
  template:
    metadata:
      labels:
        app: nginx
    spec:
      replicas: 3
      selector:
        matchLabels:
          app: nginx
      template:
        metadata:
          labels:
            app: nginx
        spec:
          containers:
          - image: eslih/webapp-nginx:v1.0.1
            name: nginx
            resources:
              requests:
                cpu: "100m"
              limits:
                cpu: "200m"
            ports:
              - containerPort: 80

  placement:
    clusters:
      - name: euw1
      - name: usc1
      - name: eks


