apiVersion: types.kubefed.io/v1beta1
kind: FederatedDeployment
metadata:
  name: webapp
  namespace: webapp
spec:
  template:
    metadata:
      labels:
        app: nginx
    spec:
      replicas: 2
      selector:
        matchLabels:
          app: webapp
      template:
        metadata:
          labels:
            app: webapp
        spec:
          containers:
          - args:
            - uwsgi
            - --ini
            - app.ini
            image: vanherpedries/webapp:latest
            name: webapp
            resources: 
              requests: 
                cpu: "100m"
              limits:
                cpu: "200m"

          restartPolicy: Always
  placement:
    clusters:
      - name: euw1
      - name: usc1
      - name: eks